{{/*---*/}}
{{/*apiVersion: security.istio.io/v1beta1*/}}
{{/*kind: AuthorizationPolicy*/}}
{{/*metadata:*/}}
{{/*  name: deadend*/}}
{{/*  namespace: {{ .Release.Namespace }}*/}}
{{/*spec:*/}}
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      app: deadend*/}}
{{/*  action: ALLOW*/}}
{{/*  rules:*/}}
{{/*    - to:*/}}
{{/*        - operation:*/}}
{{/*            ports: [ "22", "8118" ]*/}}
{{/*    - from:*/}}
{{/*        - source:*/}}
{{/*            namespaces:*/}}
{{/*              - {{ .Release.Namespace }}*/}}
