{{/*---*/}}
{{/*apiVersion: networking.istio.io/v1beta1*/}}
{{/*kind: DestinationRule*/}}
{{/*metadata:*/}}
{{/*  name: deadendproxy*/}}
{{/*  namespace: {{ .Release.Namespace }}*/}}
{{/*spec:*/}}
{{/*  host: deadendproxy.{{ .Release.Namespace }}.svc.cluster.local*/}}
{{/*  exportTo:*/}}
{{/*    - "*"*/}}
{{/*  trafficPolicy:*/}}
{{/*    tls:*/}}
{{/*      mode: ISTIO_MUTUAL*/}}
{{/*    connectionPool:*/}}
{{/*      tcp:*/}}
{{/*        maxConnections: 100*/}}
