---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: deadend-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - deadend-{{ .Release.Namespace }}.{{ .Values.domain }}
      port:
        name: tcp-ssh
        number: 2222
        protocol: TCP
