# The configmap can dynamically be updated
# Command that needs to be run in the container after configmap update is:
# rsync -iL --stats --chown=teknoir:teknoir -chmod=600 /secret-keys/* /home/teknoir/.ssh/
---
apiVersion: v1
kind: Secret
metadata:
  name: deadend-authorized-keys-secret
  namespace: {{ .Release.Namespace }}
stringData:
  authorized_keys: |
    {{ .Values.authorizedKeys | indent 4 }}
