---
apiVersion: v1
kind: Service
metadata:
  name: deadend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: deadend
  ports:
    - name: tcp-ssh
      port: 2222
      targetPort: 22
      protocol: TCP
