---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notebook-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
data:
{{- range $key, $value := .Values.parameters }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
