---
apiVersion: v1
kind: Service
metadata:
  name: notebook-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
spec:
  ports:
  - port: 443
  selector:
    {{- toYaml .Values.commonLabels | nindent 4 }}
