---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: emqx-bootstrap-api-keys
  namespace: {{ .Release.Namespace }}
data:
  apiKey: {{ include "emqx.apiKey_b64" . | quote }}
  apiSecret: {{ include "emqx.apiSecret_b64" . | quote }}
  api-keys.txt: {{ printf "%s:%s" (include "emqx.apiKey_b64" .) (include "emqx.apiSecret_b64" .) | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: emqx-bootstrap-user
  namespace: {{ .Release.Namespace }}
  labels:
    app: emqx
type: Opaque
data:
  username: {{ include "emqx.username_b64" . | quote }}
  password: {{ include "emqx.password_b64" . | quote }}
