---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: emqx-bootstrap-api-keys
  namespace: {{ .Release.Namespace }}
data:
  api-keys.txt: {{ printf "%s:%s" .Values.emqx.apiKey .Values.emqx.apiSecret | b64enc }}
