---
{{- $apiKey := (include "emqx.apiKey" .) -}}
{{- $apiSecret := (include "emqx.apiSecret" .) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: emqx-bootstrap-api-keys
  namespace: {{ .Release.Namespace }}
  labels:
    app: emqx
data:
  apiKey: {{ $apiKey | b64enc | quote }}
  apiSecret: {{ $apiSecret | b64enc | quote }}
  api-keys.txt: {{ printf "%s:%s" $apiKey $apiSecret | b64enc | quote }}

---
{{- $username := ( include "emqx.username" .) -}}
{{- $password := ( include "emqx.password" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: emqx-bootstrap-user
  namespace: {{ .Release.Namespace }}
  labels:
    app: emqx
type: Opaque
data:
  username: {{ $username | b64enc | quote }}
  password: {{ $password | b64enc | quote }}
  brokerURL: {{ printf "mqtt://emqx.%s:1883" .Release.Namespace| b64enc | quote }}
