---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mqtt-ws
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - 'mqtt-{{ .Release.Namespace }}.{{ .Values.domain }}'
  gateways:
    - istio-system/teknoir-gateway-public
  http:
    - route:
        - destination:
            host: emqx-headless.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8083

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mqtt
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - 'mqtt-{{ .Release.Namespace }}.{{ .Values.domain }}'
  gateways:
    - istio-system/teknoir-gateway-public
  tcp:
    - match:
        - port: 8883
      route:
        - destination:
            host: emqx-headless.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 1883

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: emqx-dashboard
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - 'emqx-dashboard-{{ .Release.Namespace }}.{{ .Values.domain }}'
  gateways:
    - istio-system/teknoir-gateway
  http:
    - route:
        - destination:
            host: emqx.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 18083


