apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    teknoir.org/activity-logs-enabled: "true"
    teknoir.org/activity-logs-section: prometheus
  name: prometheus
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
    {{- if .Values.thanos.enabled }}
    - name: grpc-sidecar
      port: 19090
      protocol: TCP
      targetPort: 19090
    {{- end }}
  selector:
    app: prometheus
  sessionAffinity: None
