apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
  name: {{ .Release.Namespace }}-prometheus-config
  namespace: {{ .Release.Namespace }}
data:
  user_defined_rules.yml: |
    groups: []
