apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
    teknoir.org/activity-logs-enabled: "true"
    teknoir.org/activity-logs-section: prometheus
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
    {{- if .Values.thanos.enabled }}
    - name: grpc-sidecar
      port: 19090
      protocol: TCP
      targetPort: 19090
    {{- end }}
  selector:
    app: {{ .Values.name }}
  sessionAffinity: None
