apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.name }}-vsvc
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  gateways:
  - istio-system/teknoir-gateway
  hosts:
  - {{ .Values.domainPrefix }}{{ if .Values.domainPrefix }}.{{ end }}{{ .Values.domain }}
  http:
  - match:
    - uri:
        prefix: /{{ .Values.namespace | default .Release.Namespace }}/{{ .Values.name }}
    rewrite:
      uri: /{{ .Values.namespace | default .Release.Namespace }}/{{ .Values.name }}
    route:
    - destination:
        host: {{ .Values.name }}.{{ .Values.namespace | default .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
