{{- if .Values.thanos.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thanos-query
    teknoir.org/activity-logs-enabled: "true"
    teknoir.org/activity-logs-section: prometheus
  name: thanos-query
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: thanos-query
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: thanos-query
        teknoir.org/activity-logs-enabled: "true"
        teknoir.org/activity-logs-section: prometheus
    spec:
      serviceAccountName: {{ .Values.name }}
      serviceAccount: {{ .Values.name }}
      containers:
        - name: thanos-query
          image: "quay.io/thanos/thanos:{{ .Values.thanosVersion }}"
          imagePullPolicy: Always
          args:
            - query
            - --http-address=0.0.0.0:9090
            - --web.external-prefix={{ .Values.namespace | default .Release.Namespace }}/thanos
            - --web.prefix-header=X-Forwarded-Prefix
            - --grpc-address=0.0.0.0:10901
            - --endpoint={{ .Values.name }}.{{ .Values.namespace | default .Release.Namespace }}.svc.cluster.local:19090
            - --endpoint=thanos-store-svc.{{ .Values.namespace | default .Release.Namespace }}.svc.cluster.local:19090
            - --log.level=debug
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
{{- end }}
