apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "profile-controller.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "profile-controller.labels" . | nindent 4 }}
data:
  ADMIN: {{ .Values.config.admin | quote }}
  WORKLOAD_IDENTITY: {{ .Values.config.workloadIdentity | quote }}
  USERID_HEADER: {{ .Values.config.userIdHeader | quote }}
  USERID_PREFIX: {{ .Values.config.userIdPrefix | quote }}
  PROJECT_ID: {{ .Values.config.projectId | quote }}
  DOMAIN: {{ .Values.config.domain | quote }}
  DOMAIN_PREFIX: {{ .Values.config.domainPrefix | quote }}
  REGION: {{ .Values.config.region | quote }}
  DNS_ZONE: {{ .Values.config.dnsZone | quote }}
  ISTIO_REVISION: {{ .Values.config.istioRevision | quote }}
