---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backstage
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
    - istio-system/teknoir-gateway
  hosts:
    - {{ .Values.config.domain | quote }}
  http:
    - match:
        - uri:
            prefix: /api/
      route:
        - destination:
            host: backstage-api.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
    - route:
        - destination:
            host: backstage.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
