---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-k8s-sa-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: backstage-api
type: kubernetes.io/service-account-token