apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "user-controller.fullname" . }}
  labels:
    {{- include "user-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
