name: prometheus
namespace: ""
domain: teknoir.online
domainPrefix: ""
persistentVolumeClaimSize: 15Gi
version: v2.52.0
thanosVersion: v0.39.2
serviceAccountName: prometheus

thanos:
  enabled: false
  compactor:
    enabled: true
    storage: 150Gi
