domain: teknoir.online
domainPrefix:
persistentVolumeClaimSize: 15Gi
prometheusVersion: v2.52.0
thanosVersion: v0.39.2
serviceAccountName: default-editor

thanos:
  enabled: false
  compactor:
    enabled: true
    storage: 150Gi
