apiVersion: v2
name: profile-plugin-emqx
description: A Helm chart for EMQX used by Profile Controller
type: application
version: 0.0.10
appVersion: "v5.8.9"
dependencies:
  - name: emqx
    version: "5.8.9"
    repository: https://repos.emqx.io/charts